---
 
apiVersion: extensions/v1beta1
 
kind: Deployment
 
metadata:
 
  name: tomcat
 
spec:
 
  replicas: 2
 
  template:
 
    metadata:
 
      labels:
 
        app: tomcat
 
    spec:
 
      containers:
 
        - name: tomcat
 
          image: edithwu/kubernetes:ebook_back
 
          ports:
 
            - containerPort: 8080
