
---
apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    name: front
spec:
  type: NodePort  
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32145   
  selector:
    app: front
