
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    name: tomcat
spec:
  type: NodePort  
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32143   
  selector:
    app: tomcat
